name: Attach avatars to release assets

on:
  release:
    types:
      - released
      - prereleased
  workflow_dispatch:

jobs:
  pack_figura_avatar:
    name: Pack avatar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: "auto"
      - name: Set up Python 3.14.3
        run: uv python install 3.14.3
      - name: Install dependencies for build scripts
        run: uv sync
        working-directory: ./build_scripts/
      - name: Build avatars
        run: uv run build.py -r
        working-directory: ./build_scripts/
      - name: Move license files
        run: |
          mv ./LICENSE ./dist/LICENSE
      - name: Install dependencies for readme generation scripts
        run: uv sync
        working-directory: ./readme_scripts/
      - name: Generate readmes
        run: uv run generate_readme_txt.py ${TAG_NAME} ${RELEASE_DATE}
        env:
          TAG_NAME: "v3.0.0"
          RELEASE_DATE: "2026/04/26"
        working-directory: ./readme_scripts/
      - name: Move readme
        run: |
          mv ./README.txt ./dist/README.txt
          mv ./お読みください.txt ./dist/お読みください.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: figura_blue_archive_crafters
          path: ./dist/
  attach_avatar:
    name: Attach avatars to release assets
    needs: pack_figura_avatar
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.3.0
        with:
          name: figura_blue_archive_crafters
          path: ./
      - name: Zip artifact
        run: zip -r figura_blue_archive_crafters.zip ./
      - name: Attach artifacts to release assets
        run: gh release upload ${TAG_NAME} ./figura_blue_archive_crafters.zip --repo ${REPOSITORY}
        env:
          GH_TOKEN: ${{ github.token }}
          TAG_NAME: ${{ github.event.release.tag_name }}
          REPOSITORY: ${{ github.repository }}
