name: Attach avatars to release assets

on:
  release:
    types:
      - released
      - prereleased

jobs:
  pack_figura_avatar:
    name: Pack avatar
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - extra_args: ""
            artifact_name: FiguraBlueArchiveCrafters-figura0.1.5+1.16.5-1.21.4
          - extra_args: "-n"
            artifact_name: FiguraBlueArchiveCrafters-figura0.1.5+1.21.5-1.21.11
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: "auto"
      - name: Install pngquant
        run: sudo apt install -y pngquant
      - name: Set up Python 3.14.3
        run: uv python install 3.14.3
      - name: Install dependencies for build scripts
        run: uv sync
        working-directory: ./build_scripts/
      - name: Build avatars
        run: uv run build.py -r ${{ matrix.extra_args }}
        working-directory: ./build_scripts/
      - name: Move license files
        run: |
          mv ./LICENSE ./dist/LICENSE
      - name: Install dependencies for readme generation scripts
        run: uv sync
        working-directory: ./readme_scripts/
      - name: Generate readmes
        run: uv run generate_readme_txt.py ${TAG_NAME} ${RELEASE_DATE}
        env:
          TAG_NAME: ${{ github.ref_name }}
          RELEASE_DATE: ${{ github.event.release.created_at }}
        working-directory: ./readme_scripts/
      - name: Move readme
        run: |
          mv ./README.txt ./dist/README.txt
          mv ./お読みください.txt ./dist/お読みください.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ matrix.artifact_name }}
          path: ./dist/
  attach_avatar:
    name: Attach avatars to release assets
    needs: pack_figura_avatar
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.3.0
        with:
          path: ./artifacts
      - name: Zip artifact
        run: |
          for dir in */; do
            dir_name=${dir%/}
            cd "$dir_name"
            zip -r "../${dir_name}.zip" ./*
            cd ..
          done
        working-directory: ./artifacts
      - name: Attach artifacts to release assets
        run: gh release upload ${TAG_NAME} ./*.zip --repo ${REPOSITORY}
        env:
          GH_TOKEN: ${{ github.token }}
          TAG_NAME: ${{ github.event.release.tag_name }}
          REPOSITORY: ${{ github.repository }}
        working-directory: ./artifacts
