name: Generate readme

on:
  push:
    branches:
      - main
    paths:
      - readme_scripts/**
      - .github/workflows/generate_readme.yml

jobs:
  generate:
    name: Generate readme
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: "auto"
      - name: Install dependencies
        run: uv sync
        working-directory: ./readme_scripts/
      - name: Generate readmes
        run: uv run generate_readme_md.py
        working-directory: ./readme_scripts/
      - id: check_diff
        name: Check diff
        continue-on-error: true
        run: |
          git add -N --all
          git diff --exit-code
      - name: Commit and push
        if: ${{ steps.check_diff.outcome == 'failure' }}
        run: |
          git remote set-url origin https://github-actions:${{ github.token }}@github.com/${{ github.repository }}
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add --all
          git commit -m '[GitHub Actions] ドキュメントの自動生成' -m '対象のコミット: ${{ github.sha }}'
          git push origin
